---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
data:
  update-node.sh: |
    #!/bin/bash
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |-
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1

    appendonly yes
    appendfsync everysec
    protected-mode no

    dir /data
    tcp-backlog 511
    bind 0.0.0.0
    maxclients 1000
    pidfile /data/redis.pid

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-cluster-pv-volume
#   labels:
#     type: local
#     app: redis-cluster
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/redis-cluster"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-cluster-pv-claim
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
#   selector:
#     matchLabels:
#       app: redis-cluster

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  replicas: 6
  serviceName: redis-cluster
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:5
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        # "/conf/update-node.sh", 
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        resources:
          limits:
            memory: 200Mi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: redis-data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster
          defaultMode: 0755
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: redis-cluster-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard