# -- Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitgo
  labels:
    app: bitgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitgo
  template:
    metadata:
      labels:
        app: bitgo
    spec:
      containers:
      - name: bitgo
        image: bitgosdk/express:latest
        ports:
        - containerPort: 3080

---
# -- Service

apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitgo
    env: dev
  name: bitgo
spec:
  type: NodePort
  selector:
    app: bitgo
  ports:
  - port: 3080
    targetPort: 3080
    nodePort: 32080
  