apiVersion: v1
kind: Service
metadata:
 name: bitgo-jober
spec:
 type: ClusterIP
 ports:
 - port: 8502
   targetPort: 8502

---

apiVersion: v1
kind: Endpoints
metadata:
 name: bitgo-jober
subsets:
 - addresses:
     - ip: 192.168.154.135
   ports:
     - port: 8502