apiVersion: v1
kind: ConfigMap
metadata:
  name: xxl-job-cm
data:
  PARAMS: "--spring.datasource.url=jdbc:mysql://mysql.default.svc.cluster.local:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=123456 "

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job
  labels:
    app: xxl-job
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job
  template:
    metadata:
      labels:
        app: xxl-job
        env: dev
    spec:
      containers:
      - name: xxl-job
        image: xuxueli/xxl-job-admin:2.2.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 800m
            memory: 512Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: PARAMS
          valueFrom:
            configMapKeyRef:
              name: xxl-job-cm
              key: PARAMS
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: xxl-job
  labels:
    app: xxl-job
    env: dev
spec:
  selector:
    app: xxl-job
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
  type: NodePort